### ISSUE TITLE
BUG: rvzr accessing /home/t-oleksenkoo 

### ISSUE THREAD

**Issue by CoolBlueSam** [microsoft/sca-fuzzer#106]
Followed the steps on README and ran rvzr fuzz command with -c demo/conf-v1.yaml.

Get the following error:
It seems it is trying to access /home/t-oleksenkoo/bin/binutils-gdb/gas/as-new

INFO: [prog_gen] Setting program_generator_seed to random value: 53533
**/bin/sh: 1: /home/t-oleksenkoo/bin/binutils-gdb/gas/as-new: not found**

Traceback (most recent call last):
  File "/root/venv-revizor/bin/rvzr", line 8, in <module>
    sys.exit(main())
  File "/root/venv-revizor/lib/python3.10/site-packages/revizor/cli.py", line 237, in main
    exit_code = fuzzer.start(
  File "/root/venv-revizor/lib/python3.10/site-packages/revizor/x86/x86_fuzzer.py", line 80, in start
    return super().start(num_test_cases, num_inputs, timeout, nonstop)
  File "/root/venv-revizor/lib/python3.10/site-packages/revizor/fuzzer.py", line 93, in start
    test_case = self.generator.create_test_case('generated.asm')
  File "/root/venv-revizor/lib/python3.10/site-packages/revizor/generator.py", line 135, in create_test_case
    self.assemble(asm_file, bin_file)
  File "/root/venv-revizor/lib/python3.10/site-packages/revizor/generator.py", line 169, in assemble
    raise e
  File "/root/venv-revizor/lib/python3.10/site-packages/revizor/generator.py", line 162, in assemble
    out = run(f"/home/t-oleksenkoo/bin/binutils-gdb/gas/as-new {asm_file} -o {bin_file}", shell=True, check=True, capture_output=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,

**Comment by OleksiiOleksenko** [comment]
Hi. Thanks for reporting! This issue should be fixed now if you install the latest version of the package: https://pypi.org/project/revizor-fuzzer
